### ISSUE TITLE
It does not work with hexo 3.0

### ISSUE THREAD

**Issue by orangeclk** [wzpan/hexo-renderer-pandoc#1]
I got the error information as below when I run the command 'hexo generate'

/home/orangeclk/blog/node_modules/hexo-renderer-pandoc/index.js:20
        error += data();
                 ^
TypeError: object is not a function
    at Socket.<anonymous> (/home/orangeclk/blog/node_modules/hexo-renderer-pandoc/index.js:20:12)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:526:21)

The environment is:
hexo: 3.0.0
os: Linux 3.16.0-24-generic linux x64
http_parser: 1.0
node: 0.10.25
v8: 3.14.5.9
ares: 1.10.0
uv: 0.10.23
zlib: 1.2.8
modules: 11
openssl: 1.0.1f

**Comment by wzpan** [comment]
Have you installed pandoc?

**Comment by orangeclk** [comment]
Part of the pandoc versioin information:

pandoc 1.12.4.2
Compiled with texmath 0.6.6.1, highlighting-kate 0.5.8.5.

Thanks!

**Comment by wzpan** [comment]
OK. I will update to Hexo 3.0 and find out what's wrong with this renderer.  Thanks.

**Comment by wzpan** [comment]
By the way, have you ever use my renderer under hexo 2.x? Or this is your first try?

**Comment by wzpan** [comment]
Hi @orangeclk , I guess I have fixed the issue. Will you please upgrade and try it again? ;-)

**Comment by orangeclk** [comment]
Thanks a lot! It really works now~
I have used pandoc renderer under hexo 2.x. But hexo 3.0 is a quite different version so that I setup a new hexo 3.0 environment and then I found that the render cannot work under the new 3.0 environment.
Anyway, it works without any errors now!

**Comment by wzpan** [comment]
Great. 😄
